### ISSUE TITLE
Selecting icon text and file dialog text in Cinnamon creates a visual bug.

### ISSUE THREAD

**Issue by LinuxBeaver** [TerminalHash/Modern#9]
Preview of visual bug here.
![image](https://github.com/TerminalHash/Modern/assets/78667207/7462a9f5-0401-4738-9be1-9dcfeab6f244)

This problem occurs on Cinnamon 4.8.

**Comment by TerminalHash** [comment]
Hi! I know about this bug, I'll fix it now.

**Comment by TerminalHash** [comment]
Changed the highlight color in general to a more appropriate + text color, apparently accidentally copied from the black theme :sweat_smile:
